### ISSUE TITLE
[Errno 2] No such file or directory: 'stylegan2-ffhq-config-f.pt'

### ISSUE THREAD

**Issue by molo32** [orpatashnik/StyleCLIP#7] opened 2021-02-16 20:10 UTC
error in colab 

[Errno 2] No such file or directory: 'stylegan2-ffhq-config-f.pt'

```
from main import main
from argparse import Namespace
result = main(Namespace(**args))


---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-fbc1a59be2c9> in <module>()
      1 from main import main
      2 from argparse import Namespace
----> 3 result = main(Namespace(**args))

3 frames
/usr/local/lib/python3.6/dist-packages/torch/serialization.py in __init__(self, name, mode)
    209 class _open_file(_opener):
    210     def __init__(self, name, mode):
--> 211         super(_open_file, self).__init__(open(name, mode))
    212 
    213     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: 'stylegan2-ffhq-config-f.pt'
```

**Comment by molo32** [comment] 2021-02-16 20:19
found out there is no permission to download from drive

```
Permission denied: https://drive.google.com/uc?id=1EM87UquaoQmk17Q8d5kYIAHqu0dkYqdT
Maybe you need to change permission over 'Anyone with the link'?
```

**Comment by woctezuma** [comment] 2021-02-16 20:21
Yes, the Google Drive quota has been reached.

**Comment by woctezuma** [comment] 2021-02-16 20:25
Try this:
- for PyTorch: https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/transfer-learning-source-nets/ffhq-res1024-mirror-stylegan2-noaug.pkl
- for TensforFlow 1: https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada/pretrained/transfer-learning-source-nets/ffhq-res1024-mirror-stylegan2-noaug.pkl

**Comment by ramtiin** [comment] 2021-02-16 22:59
You can also try using PyDrive, it worked for me:


```
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

file_id = '1EM87UquaoQmk17Q8d5kYIAHqu0dkYqdT'
downloaded = drive.CreateFile({'id':file_id})
downloaded.FetchMetadata(fetch_all=True)
downloaded.GetContentFile(downloaded.metadata['title'])

```

**Comment by orpatashnik** [comment] 2021-02-16 23:13
Thanks @woctezuma and @ramtiin !
@molo32 please close the issue if the problem is solved, and let me know if you need further help

**Comment by n00mkrad** [comment] 2021-02-17 12:56
Issue persists.

The file should either be hosted somewhere without those traffic limits, or the code should be modified to use something like PyDrive as that seems to work for @ramtiin.

**Comment by orpatashnik** [comment] 2021-02-18 11:47
Hi @n00mkrad ,

I can reproduce the problem, but I change the code so that it will use the solution that worked for @ramtiin .
Can you check if it solves the problem?

**Comment by n00mkrad** [comment] 2021-02-18 18:40
Works now.

**Comment by orpatashnik** [comment] 2021-02-18 19:00
cool

**Closed by orpatashnik** 2021-02-18 19:00 UTC
